/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const LineItem = IDL.Record({
  'qty' : IDL.Nat,
  'date' : Time,
  'description' : IDL.Text,
  'discount' : IDL.Nat,
  'category' : IDL.Text,
  'basePrice' : IDL.Nat,
  'appliedCharge' : IDL.Nat,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const Doctor = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'specialization' : IDL.Text,
  'phone' : IDL.Text,
});
export const SuratKeteranganSehat = IDL.Record({
  'id' : IDL.Nat,
  'weight' : IDL.Nat,
  'height' : IDL.Nat,
  'doctorId' : IDL.Nat,
  'patientId' : IDL.Nat,
  'bloodPressure' : IDL.Text,
  'issuedDate' : Time,
  'notes' : IDL.Text,
  'pulse' : IDL.Nat,
  'purpose' : IDL.Text,
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'lineItems' : IDL.Vec(LineItem),
  'patientId' : IDL.Nat,
  'dateOfPrinting' : Time,
  'payer' : IDL.Opt(IDL.Text),
  'registrationDate' : Time,
  'regNo' : IDL.Text,
});
export const Patient = IDL.Record({
  'id' : IDL.Nat,
  'patientNo' : IDL.Text,
  'dateOfBirth' : Time,
  'name' : IDL.Text,
  'createdAt' : Time,
  'address' : IDL.Text,
  'gender' : Gender,
  'phone' : IDL.Text,
});
export const ServiceCatalog = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'basePrice' : IDL.Nat,
});
export const SuratKeteranganSakit = IDL.Record({
  'id' : IDL.Nat,
  'doctorId' : IDL.Nat,
  'endDate' : Time,
  'patientId' : IDL.Nat,
  'diagnosis' : IDL.Text,
  'issuedDate' : Time,
  'notes' : IDL.Text,
  'restDays' : IDL.Nat,
  'startDate' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDoctor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'createHealthCertificate' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        Time,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'createInvoice' : IDL.Func(
      [
        IDL.Nat,
        Time,
        IDL.Text,
        IDL.Opt(IDL.Text),
        Time,
        IDL.Text,
        IDL.Vec(LineItem),
      ],
      [],
      [],
    ),
  'createPatient' : IDL.Func(
      [IDL.Text, Time, Gender, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createService' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'createSickNote' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, Time, Time, IDL.Nat, Time, IDL.Text],
      [],
      [],
    ),
  'deleteDoctor' : IDL.Func([IDL.Nat], [], []),
  'deleteHealthCertificate' : IDL.Func([IDL.Nat], [], []),
  'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
  'deletePatient' : IDL.Func([IDL.Nat], [], []),
  'deleteService' : IDL.Func([IDL.Nat], [], []),
  'deleteSickNote' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getHealthCertificates' : IDL.Func(
      [],
      [IDL.Vec(SuratKeteranganSehat)],
      ['query'],
    ),
  'getInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(ServiceCatalog)], ['query']),
  'getSickNotes' : IDL.Func([], [IDL.Vec(SuratKeteranganSakit)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDoctor' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updatePatient' : IDL.Func(
      [IDL.Nat, IDL.Text, Time, Gender, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateService' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const LineItem = IDL.Record({
    'qty' : IDL.Nat,
    'date' : Time,
    'description' : IDL.Text,
    'discount' : IDL.Nat,
    'category' : IDL.Text,
    'basePrice' : IDL.Nat,
    'appliedCharge' : IDL.Nat,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Doctor = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'specialization' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SuratKeteranganSehat = IDL.Record({
    'id' : IDL.Nat,
    'weight' : IDL.Nat,
    'height' : IDL.Nat,
    'doctorId' : IDL.Nat,
    'patientId' : IDL.Nat,
    'bloodPressure' : IDL.Text,
    'issuedDate' : Time,
    'notes' : IDL.Text,
    'pulse' : IDL.Nat,
    'purpose' : IDL.Text,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'lineItems' : IDL.Vec(LineItem),
    'patientId' : IDL.Nat,
    'dateOfPrinting' : Time,
    'payer' : IDL.Opt(IDL.Text),
    'registrationDate' : Time,
    'regNo' : IDL.Text,
  });
  const Patient = IDL.Record({
    'id' : IDL.Nat,
    'patientNo' : IDL.Text,
    'dateOfBirth' : Time,
    'name' : IDL.Text,
    'createdAt' : Time,
    'address' : IDL.Text,
    'gender' : Gender,
    'phone' : IDL.Text,
  });
  const ServiceCatalog = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'basePrice' : IDL.Nat,
  });
  const SuratKeteranganSakit = IDL.Record({
    'id' : IDL.Nat,
    'doctorId' : IDL.Nat,
    'endDate' : Time,
    'patientId' : IDL.Nat,
    'diagnosis' : IDL.Text,
    'issuedDate' : Time,
    'notes' : IDL.Text,
    'restDays' : IDL.Nat,
    'startDate' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDoctor' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'createHealthCertificate' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          Time,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'createInvoice' : IDL.Func(
        [
          IDL.Nat,
          Time,
          IDL.Text,
          IDL.Opt(IDL.Text),
          Time,
          IDL.Text,
          IDL.Vec(LineItem),
        ],
        [],
        [],
      ),
    'createPatient' : IDL.Func(
        [IDL.Text, Time, Gender, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createService' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'createSickNote' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, Time, Time, IDL.Nat, Time, IDL.Text],
        [],
        [],
      ),
    'deleteDoctor' : IDL.Func([IDL.Nat], [], []),
    'deleteHealthCertificate' : IDL.Func([IDL.Nat], [], []),
    'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
    'deletePatient' : IDL.Func([IDL.Nat], [], []),
    'deleteService' : IDL.Func([IDL.Nat], [], []),
    'deleteSickNote' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getHealthCertificates' : IDL.Func(
        [],
        [IDL.Vec(SuratKeteranganSehat)],
        ['query'],
      ),
    'getInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(ServiceCatalog)], ['query']),
    'getSickNotes' : IDL.Func([], [IDL.Vec(SuratKeteranganSakit)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDoctor' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updatePatient' : IDL.Func(
        [IDL.Nat, IDL.Text, Time, Gender, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateService' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };