/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Doctor {
  'id' : bigint,
  'name' : string,
  'specialization' : string,
  'phone' : string,
}
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface Invoice {
  'id' : bigint,
  'status' : string,
  'lineItems' : Array<LineItem>,
  'patientId' : bigint,
  'dateOfPrinting' : Time,
  'payer' : [] | [string],
  'registrationDate' : Time,
  'regNo' : string,
}
export interface LineItem {
  'qty' : bigint,
  'date' : Time,
  'description' : string,
  'discount' : bigint,
  'category' : string,
  'basePrice' : bigint,
  'appliedCharge' : bigint,
}
export interface Patient {
  'id' : bigint,
  'patientNo' : string,
  'dateOfBirth' : Time,
  'name' : string,
  'createdAt' : Time,
  'address' : string,
  'gender' : Gender,
  'phone' : string,
}
export interface ServiceCatalog {
  'id' : bigint,
  'name' : string,
  'category' : string,
  'basePrice' : bigint,
}
export interface SuratKeteranganSakit {
  'id' : bigint,
  'doctorId' : bigint,
  'endDate' : Time,
  'patientId' : bigint,
  'diagnosis' : string,
  'issuedDate' : Time,
  'notes' : string,
  'restDays' : bigint,
  'startDate' : Time,
}
export interface SuratKeteranganSehat {
  'id' : bigint,
  'weight' : bigint,
  'height' : bigint,
  'doctorId' : bigint,
  'patientId' : bigint,
  'bloodPressure' : string,
  'issuedDate' : Time,
  'notes' : string,
  'pulse' : bigint,
  'purpose' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDoctor' : ActorMethod<[string, string, string], undefined>,
  'createHealthCertificate' : ActorMethod<
    [bigint, bigint, string, Time, string, string, bigint, bigint, bigint],
    undefined
  >,
  'createInvoice' : ActorMethod<
    [bigint, Time, string, [] | [string], Time, string, Array<LineItem>],
    undefined
  >,
  'createPatient' : ActorMethod<
    [string, Time, Gender, string, string],
    undefined
  >,
  'createService' : ActorMethod<[string, string, bigint], undefined>,
  'createSickNote' : ActorMethod<
    [bigint, bigint, string, Time, Time, bigint, Time, string],
    undefined
  >,
  'deleteDoctor' : ActorMethod<[bigint], undefined>,
  'deleteHealthCertificate' : ActorMethod<[bigint], undefined>,
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'deletePatient' : ActorMethod<[bigint], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'deleteSickNote' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDoctors' : ActorMethod<[], Array<Doctor>>,
  'getHealthCertificates' : ActorMethod<[], Array<SuratKeteranganSehat>>,
  'getInvoices' : ActorMethod<[], Array<Invoice>>,
  'getPatients' : ActorMethod<[], Array<Patient>>,
  'getServices' : ActorMethod<[], Array<ServiceCatalog>>,
  'getSickNotes' : ActorMethod<[], Array<SuratKeteranganSakit>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDoctor' : ActorMethod<[bigint, string, string, string], undefined>,
  'updatePatient' : ActorMethod<
    [bigint, string, Time, Gender, string, string],
    undefined
  >,
  'updateService' : ActorMethod<[bigint, string, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];